export const automationArsenal = [
    {
        name: "GCP SCC Cleaner",
        description: "Auto-formatting complex JSON to clean CSV for executive reporting",
        tech: "Apps Script",
        icons: [`${assetPath}/sheets-logo.svg`, `${assetPath}/google-apps-script.svg`],
        githubLink: "#",
    },
    {
        name: "Cloud Armor Log Batcher",
        description: "Automated analysis of 1M+ log lines to identify attack patterns",
        tech: "BigQuery",
        icons: [`${assetPath}/bash-logo.svg`],
        githubLink: "#",
    },
    {
        name: "Infrastructure Auditor",
        description: "Scanning 500+ projects for public IP exposure and firewall gaps",
        tech: "Asset Inventory",
        icons: [`${assetPath}/bash-logo.svg`, `${assetPath}/sheets-logo.svg`],
        githubLink: "#",
    },
    {
        name: "Prowler Deployer",
        description: "Automated Prowler deployment across organizations via Cloud Build",
        tech: "Cloud Build",
        icons: [`${assetPath}/bash-logo.svg`, `${assetPath}/terraform-logo.svg`],
        githubLink: "https://prowler.com",
    },
    {
        name: "IP Blacklist Checker",
        description: "Validating 1000s of IPs against abuse databases automatically",
        tech: "Threat Intel",
        icons: [`${assetPath}/sheets-logo.svg`, `${assetPath}/google-apps-script.svg`],
        githubLink: "#",
    },
    {
        name: "Cloud Armor Bulk Updater",
        description: "Updating thousands of security policies in seconds via API",
        tech: "GCP API",
        icons: [`${assetPath}/bash-logo.svg`],
        githubLink: "#",
    },
    {
        name: "SSL Policy Manager",
        description: "Forcing TLS 1.2+ across all load balancers in the organization",
        tech: "Security",
        icons: [`${assetPath}/bash-logo.svg`, `${assetPath}/python-logo.svg`],
        githubLink: "#",
    },
    {
        name: "SCC Alert Router",
        description: "Routing critical alerts to Jira/Slack based on severity & project",
        tech: "Pub/Sub",
        icons: [`${assetPath}/bash-logo.svg`, `${assetPath}/terraform-logo.svg`, `${assetPath}/python-logo.svg`],
        githubLink: "#",
    },
    {
        name: "IAM Recommender Parser",
        description: "Parsing IAM recommendations to identify over-privileged accounts",
        tech: "IAM",
        icons: [`${assetPath}/python-logo.svg`],
        githubLink: "#",
    },
    {
        name: "Gemini Report Generator",
        description: "Using GenAI to summarize weekly security incidents for C-suite",
        tech: "GenAI",
        icons: [`${assetPath}/gemini-logo.svg`, `${assetPath}/sheets-logo.svg`, `${assetPath}/google-apps-script.svg`],
        githubLink: "#",
    },
];
